### ISSUE TITLE
Plan the application's layout/architecture/workflow

### ISSUE THREAD

**Issue by ErlingHauan** [ErlingHauan/FormFactory#20]
- [x] #22 
- [x] How is the two frontend apps and the backend going to interact with each other?
  - The main app will import the form creator as a component.
  - To begin with, the backend will have three endpoints for forms. The form creator will POST the form template to persistent storage. The form viewer will have its own POST to submit the form with data, and validate the entries against the template. Lastly, there will be a GET endpoint to retrieve the form. 
- [x] What are the features that the application has to have?
  - Text inputs for the form
  - Multiple choice
  - Form viewer
  - Answer viewer
  - Authentication
  - Optional: output file should be readable by Excel
- [x] What will be the boundaries of the two frontends?
  - The main app will have a header and a footer. The form creator app will be displayed inside the main application. The main application will also take care of authentication and displaying the forms.
- [x] How to make a flexible backend? Validation need to be handled by the backend as well as the frontend.
  - When a form is created by its owner, a template will be made. The backend will use this template to validate the submitted form.
- [x] #21
